-- MySQL Script generated by MySQL Workbench
-- Tue May 17 04:18:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ATMManagementDB
-- -----------------------------------------------------
SET SQL_SAFE_UPDATES = 0; 
CREATE DATABASE IF NOT EXISTS ATMManagementDB;
USE ATMManagementDB;
-- -----------------------------------------------------
-- Table `GeneralUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeneralUser` ;

CREATE TABLE IF NOT EXISTS `GeneralUser` (
  `general_user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(128) NULL,
  `ssn` INT NULL,
  `address` VARCHAR(128) NULL,
  `is_verified` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`general_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank` ;

CREATE TABLE IF NOT EXISTS `Bank` (
  `bank_id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `address` VARCHAR(128) NULL,
  PRIMARY KEY (`bank_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `employee_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `bank_id` INT NOT NULL,
  `isAdmin` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`employee_id`),
  INDEX `FK_bank_employee_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `FK_bank_employee`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `admin_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `privileges` VARCHAR(128) NULL,
  PRIMARY KEY (`admin_id`, `employee_id`),
  INDEX `FK_empl_admin_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_employee_admin`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATMMachine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATMMachine` ;

CREATE TABLE IF NOT EXISTS `ATMMachine` (
  `atm_machine_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `bank_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  INDEX `FK_admin_atm_idx` (`admin_id` ASC) VISIBLE,
  INDEX `FK_bank_atm_idx` (`bank_id` ASC) VISIBLE,
  PRIMARY KEY (`atm_machine_id`),
  CONSTRAINT `FK_bank_atm`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_admin_atm`
    FOREIGN KEY (`admin_id`)
    REFERENCES `Admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manufacturer` ;

CREATE TABLE IF NOT EXISTS `Manufacturer` (
  `manufacturer_id` INT NOT NULL,
  `name` VARCHAR(128) NULL,
  `address` VARCHAR(256) NULL,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Devices` ;

CREATE TABLE IF NOT EXISTS `Devices` (
  `device_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `status` VARCHAR(64) NULL,
  `atm_machine_id` INT NOT NULL,
  `made` DATE NULL,
  PRIMARY KEY (`device_id`),
  INDEX `FK_atm_device_idx` (`atm_machine_id` ASC) VISIBLE,
  INDEX `FK_manuf_device_idx` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `FK_atm_device`
    FOREIGN KEY (`atm_machine_id`)
    REFERENCES `ATMMachine` (`atm_machine_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_manufacturer_device`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `Manufacturer` (`manufacturer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OLEDScreen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OLEDScreen` ;

CREATE TABLE IF NOT EXISTS `OLEDScreen` (
  `oled_screen_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`oled_screen_id`, `manufacturer_id`, `device_id`),
  INDEX `FK_device_oled_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_device_oledScreen`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Keypad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Keypad` ;

CREATE TABLE IF NOT EXISTS `Keypad` (
  `keypad_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`keypad_id`, `manufacturer_id`, `device_id`),
  INDEX `FK_device_keypad_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_device_keypad`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VerifiedUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VerifiedUser` ;

CREATE TABLE IF NOT EXISTS `VerifiedUser` (
  `general_user_id` INT NOT NULL,
  `privileges` TINYINT(7) NULL,
  `verified_user_id` INT NOT NULL,
  `oled_screen_id` INT NOT NULL,
  `keypad_id` INT NOT NULL,
  PRIMARY KEY (`verified_user_id`, `general_user_id`),
  INDEX `FK_oled_veruser_idx` (`oled_screen_id` ASC) VISIBLE,
  INDEX `FK_keypad_veruser_idx` (`keypad_id` ASC) VISIBLE,
  CONSTRAINT `FK_genuser_veruser`
    FOREIGN KEY (`general_user_id`)
    REFERENCES `GeneralUser` (`general_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_oled_veruser`
    FOREIGN KEY (`oled_screen_id`)
    REFERENCES `OLEDScreen` (`oled_screen_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_keypad_veruser`
    FOREIGN KEY (`keypad_id`)
    REFERENCES `Keypad` (`keypad_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CashDispenser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CashDispenser` ;

CREATE TABLE IF NOT EXISTS `CashDispenser` (
  `cash_dispenser_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`cash_dispenser_id`, `device_id`),
  INDEX `FK_device_casdis_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_device_cashDispenser`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Currency` ;

CREATE TABLE IF NOT EXISTS `Currency` (
  `currency_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `verified_user_id` INT NULL,
  `cash_dispenser_id` INT NULL,
  PRIMARY KEY (`currency_id`),
  INDEX `FK_veruser_currenc_idx` (`verified_user_id` ASC) VISIBLE,
  INDEX `FK_cashdis_currenc_idx` (`cash_dispenser_id` ASC) VISIBLE,
  CONSTRAINT `FK_verifiedUser_currency`
    FOREIGN KEY (`verified_user_id`)
    REFERENCES `VerifiedUser` (`verified_user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_cashDispenser_currency`
    FOREIGN KEY (`cash_dispenser_id`)
    REFERENCES `CashDispenser` (`cash_dispenser_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DepositCheckSlot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DepositCheckSlot` ;

CREATE TABLE IF NOT EXISTS `DepositCheckSlot` (
  `check_slot_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`check_slot_id`, `manufacturer_id`, `device_id`),
  INDEX `FK_device_check_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_device_depositCheckSlot`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Checks` ;

CREATE TABLE IF NOT EXISTS `Checks` (
  `check_id` INT NOT NULL,
  `verified_user_id` INT NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  `check_slot_id` INT NOT NULL,
  PRIMARY KEY (`check_id`),
  INDEX `FK_checkslot_check_idx` (`check_slot_id` ASC) VISIBLE,
  INDEX `FK_veruser_check_idx` (`verified_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_depositCheckSlot_checks`
    FOREIGN KEY (`check_slot_id`)
    REFERENCES `DepositCheckSlot` (`check_slot_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_verifiedUser_checks`
    FOREIGN KEY (`verified_user_id`)
    REFERENCES `VerifiedUser` (`verified_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankAccount` ;

CREATE TABLE IF NOT EXISTS `BankAccount` (
  `bank_account_id` INT NOT NULL,
  `bank_id` INT NULL,
  `general_user_id` INT NULL,
  `account_number` VARCHAR(45) NULL,
  PRIMARY KEY (`bank_account_id`),
  INDEX `FK_GENUSER_BACCOUNT_idx` (`general_user_id` ASC) VISIBLE,
  INDEX `FK_BANK_BACCOUNT_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `FK_generalUser_bankaccount`
    FOREIGN KEY (`general_user_id`)
    REFERENCES `GeneralUser` (`general_user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_bank_bankaccount`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CheckingAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CheckingAccount` ;

CREATE TABLE IF NOT EXISTS `CheckingAccount` (
  `checking_account_id` INT NOT NULL,
  `bank_account_id` INT NOT NULL,
  `balance` INT NOT NULL DEFAULT 0,
  `fees` INT NOT NULL,
  PRIMARY KEY (`checking_account_id`, `bank_account_id`),
  INDEX `FK_BACCOUNT_CACCOUNT_idx` (`bank_account_id` ASC) VISIBLE,
  CONSTRAINT `FK_bankAccount_checkingAccount`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `BankAccount` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SavingsAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SavingsAccount` ;

CREATE TABLE IF NOT EXISTS `SavingsAccount` (
  `savings_account_id` INT NOT NULL,
  `bank_account_id` INT NOT NULL,
  `balance` INT NOT NULL DEFAULT 0,
  `interest_rate` INT NOT NULL,
  PRIMARY KEY (`savings_account_id`, `bank_account_id`),
  INDEX `FK_BACCOUNT_SACCOUNT_idx` (`bank_account_id` ASC) VISIBLE,
  CONSTRAINT `FK_bankAccount_savingsAccount`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `BankAccount` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VerificationMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VerificationMethod` ;

CREATE TABLE IF NOT EXISTS `VerificationMethod` (
  `verification_method_id` INT NOT NULL,
  `verified_user_id` INT NOT NULL,
  `verification_type` VARCHAR(45) NULL,
  PRIMARY KEY (`verification_method_id`),
  INDEX `FK_veruser_vermethod_idx` (`verified_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_verifiedUser_verifiedMethod`
    FOREIGN KEY (`verified_user_id`)
    REFERENCES `VerifiedUser` (`verified_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Card` ;

CREATE TABLE IF NOT EXISTS `Card` (
  `card_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `CVV` TINYINT(3) NULL,
  `zip` VARCHAR(45) NULL,
  `exp_date` DATE NULL,
  `verification_method_id` INT NOT NULL,
  PRIMARY KEY (`card_id`, `verification_method_id`),
  INDEX `FK_vermethod_card_idx` (`verification_method_id` ASC) VISIBLE,
  CONSTRAINT `FK_verificationMethod_card`
    FOREIGN KEY (`verification_method_id`)
    REFERENCES `VerificationMethod` (`verification_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DebitCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DebitCard` ;

CREATE TABLE IF NOT EXISTS `DebitCard` (
  `debit_card_number` INT NOT NULL,
  `card_id` INT NOT NULL,
  `CVV` TINYINT(3) NULL,
  `zip` VARCHAR(45) NULL,
  `exp_date` DATE NULL,
  PRIMARY KEY (`debit_card_number`, `card_id`),
  INDEX `FK_debcard_card_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `FK_card_debitCard`
    FOREIGN KEY (`card_id`)
    REFERENCES `Card` (`card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CreditCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CreditCard` ;

CREATE TABLE IF NOT EXISTS `CreditCard` (
  `credit_card_number` INT NOT NULL,
  `card_id` INT NOT NULL,
  `CVV` TINYINT(3) NULL,
  `zip` VARCHAR(45) NULL,
  `exp_date` DATE NULL,
  PRIMARY KEY (`credit_card_number`, `card_id`),
  INDEX `FK_card_credcard_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `FK_card_creditCard`
    FOREIGN KEY (`card_id`)
    REFERENCES `Card` (`card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DigitalWallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DigitalWallet` ;

CREATE TABLE IF NOT EXISTS `DigitalWallet` (
  `wallet_id` INT NOT NULL,
  `card_number` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `verification_method_id` INT NULL,
  PRIMARY KEY (`wallet_id`, `card_number`),
  INDEX `FK_card_digwallet_idx` (`card_number` ASC) VISIBLE,
  INDEX `FK_vermethod_digwallet_idx` (`verification_method_id` ASC) VISIBLE,
  CONSTRAINT `FK_card_digitalWallet`
    FOREIGN KEY (`card_number`)
    REFERENCES `Card` (`card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_verificationMethod_digitalWallet`
    FOREIGN KEY (`verification_method_id`)
    REFERENCES `VerificationMethod` (`verification_method_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReceiptPrinter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ReceiptPrinter` ;

CREATE TABLE IF NOT EXISTS `ReceiptPrinter` (
  `receipt_printer_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`receipt_printer_id`, `manufacturer_id`, `device_id`),
  INDEX `FK_device_recpri_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_device_receiptPrinter`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transactions` ;

CREATE TABLE IF NOT EXISTS `Transactions` (
  `transactions_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `amount` INT NOT NULL,
  `atm_machine_id` INT NOT NULL,
  `bank_id` INT NOT NULL,
  `receipt_printer_id` INT NOT NULL,
  PRIMARY KEY (`transactions_id`),
  INDEX `FK_atm_trans_idx` (`atm_machine_id` ASC) VISIBLE,
  INDEX `FK_bank_trans_idx` (`bank_id` ASC) VISIBLE,
  INDEX `FK_rece_trans_idx` (`receipt_printer_id` ASC) VISIBLE,
  CONSTRAINT `FK_atm_transactions`
    FOREIGN KEY (`atm_machine_id`)
    REFERENCES `ATMMachine` (`atm_machine_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_bank_transactions`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_receiptPrinter_transactions`
    FOREIGN KEY (`receipt_printer_id`)
    REFERENCES `ReceiptPrinter` (`receipt_printer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CashWithdrawal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CashWithdrawal` ;

CREATE TABLE IF NOT EXISTS `CashWithdrawal` (
  `cash_withdrawal_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `balance` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`cash_withdrawal_id`, `transaction_id`),
  INDEX `FK_transac_cashWith_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_transaction_cashWithdrawal`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transactions` (`transactions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CashDeposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CashDeposit` ;

CREATE TABLE IF NOT EXISTS `CashDeposit` (
  `cash_deposit_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `balance` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`cash_deposit_id`, `transaction_id`),
  INDEX `FK_transac_cashdep_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `FK_transaction_cashDeposit`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transactions` (`transactions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CheckDeposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CheckDeposit` ;

CREATE TABLE IF NOT EXISTS `CheckDeposit` (
  `check_deposit_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `balance` INT NOT NULL DEFAULT 0,
  `check_slot_id` INT NOT NULL,
  PRIMARY KEY (`check_deposit_id`, `transaction_id`, `check_slot_id`),
  INDEX `FK_transac_checkdep_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `FK_slot_checkDep_idx` (`check_slot_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_transaction_checkDeposit`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transactions` (`transactions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_depositCheckSlot_checkDeposit`
    FOREIGN KEY (`check_slot_id`)
    REFERENCES `DepositCheckSlot` (`check_slot_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `payment_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `balance` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`payment_id`, `transaction_id`),
  INDEX `FK_transac_payment_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_transaction_payment`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transactions` (`transactions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transfer` ;

CREATE TABLE IF NOT EXISTS `Transfer` (
  `transfer_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `balance` INT NULL,
  PRIMARY KEY (`transfer_id`, `transaction_id`),
  INDEX `FK_transac_transfer_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_transaction_transfer`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transactions` (`transactions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SecurityAlarm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SecurityAlarm` ;

CREATE TABLE IF NOT EXISTS `SecurityAlarm` (
  `security_alarm_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `alarm_range` TINYINT(5) NULL,
  PRIMARY KEY (`security_alarm_id`),
  INDEX `FK_manuf_secalarm_idx` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `FK_manufacturer_securityAlarm`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `Manufacturer` (`manufacturer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notifications` ;

CREATE TABLE IF NOT EXISTS `Notifications` (
  `notification_id` INT NOT NULL,
  `message` VARCHAR(256) NOT NULL,
  `timestamp` TIMESTAMP NULL,
  `verified_device_id` INT NOT NULL,
  `security_alarm_id` INT NOT NULL,
  PRIMARY KEY (`notification_id`, `verified_device_id`),
  INDEX `FK_secalarm_notif_idx` (`security_alarm_id` ASC) VISIBLE,
  CONSTRAINT `FK_securityAlarm_notifications`
    FOREIGN KEY (`security_alarm_id`)
    REFERENCES `SecurityAlarm` (`security_alarm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logins` ;

CREATE TABLE IF NOT EXISTS `Logins` (
  `login_id` INT NOT NULL,
  `verified_user_id` INT NOT NULL,
  `data` VARCHAR(256) NULL,
  `logged_in` DATE NULL,
  `atm_machine_id` INT NOT NULL,
  PRIMARY KEY (`login_id`),
  INDEX `FK_veruser_login_idx` (`verified_user_id` ASC) VISIBLE,
  INDEX `FK_atmM_login_idx` (`atm_machine_id` ASC) VISIBLE,
  CONSTRAINT `FK_verifiedUser_login`
    FOREIGN KEY (`verified_user_id`)
    REFERENCES `VerifiedUser` (`verified_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_atm_login`
    FOREIGN KEY (`atm_machine_id`)
    REFERENCES `ATMMachine` (`atm_machine_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VerifiedDevices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VerifiedDevices` ;

CREATE TABLE IF NOT EXISTS `VerifiedDevices` (
  `verified_devices_id` INT NOT NULL,
  `verified_user_id` INT NOT NULL,
  `device_type` VARCHAR(45) NULL,
  PRIMARY KEY (`verified_devices_id`),
  INDEX `FK_veruser_verdevice_idx` (`verified_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_veruser_verdevice`
    FOREIGN KEY (`verified_user_id`)
    REFERENCES `VerifiedUser` (`verified_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Languages` ;

CREATE TABLE IF NOT EXISTS `Languages` (
  `language_id` INT NOT NULL,
  `language_name` VARCHAR(45) NULL,
  `country` VARCHAR(128) NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFCScanner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NFCScanner` ;

CREATE TABLE IF NOT EXISTS `NFCScanner` (
  `nfc_scanner_id` INT NOT NULL,
  `manufacturer_id` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`nfc_scanner_id`, `manufacturer_id`, `device_id`),
  INDEX `FK_device_nfc_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_device_nfcScanner`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CardReader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CardReader` ;

CREATE TABLE IF NOT EXISTS `CardReader` (
  `card_reader_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`card_reader_id`, `device_id`, `manufacturer_id`),
  INDEX `FK_device_cardRe_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_device_cardReader`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Speaker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Speaker` ;

CREATE TABLE IF NOT EXISTS `Speaker` (
  `speaker_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`speaker_id`, `manufacturer_id`, `device_id`),
  INDEX `FK_device_speaker_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK_device_speaker`
    FOREIGN KEY (`device_id`)
    REFERENCES `Devices` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Owner` ;

CREATE TABLE IF NOT EXISTS `Owner` (
  `owner_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`owner_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Affiliate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Affiliate` ;

CREATE TABLE IF NOT EXISTS `Affiliate` (
  `affiliate_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `contract` VARCHAR(128) NULL,
  PRIMARY KEY (`affiliate_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Permissions` ;

CREATE TABLE IF NOT EXISTS `Permissions` (
  `permissions_id` INT NOT NULL,
  `admin_id` VARCHAR(45) NOT NULL,
  `type` VARCHAR(128) NULL,
  `bank_account_id` INT NOT NULL,
  PRIMARY KEY (`permissions_id`, `admin_id`, `bank_account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Security`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Security` ;

CREATE TABLE IF NOT EXISTS `Security` (
  `security_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `privileges` VARCHAR(128) NULL,
  PRIMARY KEY (`security_id`, `employee_id`),
  INDEX `FK_employee_security_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_employee_security`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Analyst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Analyst` ;

CREATE TABLE IF NOT EXISTS `Analyst` (
  `analyst_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `privileges` VARCHAR(45) NULL,
  PRIMARY KEY (`analyst_id`, `employee_id`),
  INDEX `FK_employee_analyst_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_employee_analyst`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teller` ;

CREATE TABLE IF NOT EXISTS `Teller` (
  `teller_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `privileges` VARCHAR(128) NULL,
  PRIMARY KEY (`teller_id`, `employee_id`),
  INDEX `FK_employee_teller_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FK_PK_employee_teller`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Consultant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Consultant` ;

CREATE TABLE IF NOT EXISTS `Consultant` (
  `consultant_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `privileges` VARCHAR(128) NULL,
  PRIMARY KEY (`consultant_id`, `employee_id`),
  INDEX `FK_employee_consult_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FK_employee_consultant`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loans` ;

CREATE TABLE IF NOT EXISTS `Loans` (
  `loan_id` INT NOT NULL,
  `type` VARCHAR(128) NULL,
  `interest_type` VARCHAR(128) NULL,
  `bank_id` INT NOT NULL,
  `bank_account_id` INT NOT NULL,
  `terms_conditions` VARCHAR(2048) NULL,
  PRIMARY KEY (`loan_id`, `bank_id`),
  INDEX `FK_bank_loan_idx` (`bank_id` ASC) VISIBLE,
  INDEX `FK_baccount_loan_idx` (`bank_account_id` ASC) VISIBLE,
  CONSTRAINT `FK_bank_loan`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_bankAccount_loan`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `BankAccount` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Owns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Owns` ;

CREATE TABLE IF NOT EXISTS `Owns` (
  `owns_id` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `bank_id` INT NOT NULL,
  PRIMARY KEY (`owns_id`),
  INDEX `FK_bank_owns_idx` (`bank_id` ASC) VISIBLE,
  INDEX `FK_owner_owns_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `FK_bank_owns`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_owner_owns`
    FOREIGN KEY (`owner_id`)
    REFERENCES `Owner` (`owner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Received`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Received` ;

CREATE TABLE IF NOT EXISTS `Received` (
  `received_id` INT NOT NULL,
  `notification_id` INT NOT NULL,
  `verified_device_id` INT NOT NULL,
  PRIMARY KEY (`received_id`),
  INDEX `FK_verdev_received_idx` (`verified_device_id` ASC) VISIBLE,
  INDEX `FK_notif_received_idx` (`notification_id` ASC) VISIBLE,
  CONSTRAINT `FK_verifiedDevices_received`
    FOREIGN KEY (`verified_device_id`)
    REFERENCES `VerifiedDevices` (`verified_devices_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_notifications_received`
    FOREIGN KEY (`notification_id`)
    REFERENCES `Notifications` (`notification_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountPermissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountPermissions` ;

CREATE TABLE IF NOT EXISTS `AccountPermissions` (
  `account_perm_id` INT NOT NULL,
  `bank_account_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`account_perm_id`),
  INDEX `FK_perm_accperm_idx` (`permission_id` ASC) VISIBLE,
  INDEX `FK_account_accperm_idx` (`bank_account_id` ASC) VISIBLE,
  CONSTRAINT `FK_permissions_accountPermissions`
    FOREIGN KEY (`permission_id`)
    REFERENCES `Permissions` (`permissions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_account_accountPermissions`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `BankAccount` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manages` ;

CREATE TABLE IF NOT EXISTS `Manages` (
  `manage_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`manage_id`),
  INDEX `FK_admin_manage_idx` (`admin_id` ASC) VISIBLE,
  INDEX `FK_permission_manage_idx` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `FK_admin_manages`
    FOREIGN KEY (`admin_id`)
    REFERENCES `Admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_permissions_manages`
    FOREIGN KEY (`permission_id`)
    REFERENCES `Permissions` (`permissions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Affiliations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Affiliations` ;

CREATE TABLE IF NOT EXISTS `Affiliations` (
  `affiliation_id` INT NOT NULL,
  `affiliate_id` INT NULL,
  `bank_id` INT NULL,
  PRIMARY KEY (`affiliation_id`),
  INDEX `FK_affiliate_affiliation_idx` (`affiliate_id` ASC) VISIBLE,
  INDEX `FK_bank_affiliation_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `FK_affiliate_affiliation`
    FOREIGN KEY (`affiliate_id`)
    REFERENCES `Affiliate` (`affiliate_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_bank_affiliation`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Informs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Informs` ;

CREATE TABLE IF NOT EXISTS `Informs` (
  `informs_id` INT NOT NULL,
  `security_id` INT NOT NULL,
  `security_alarm_id` INT NOT NULL,
  PRIMARY KEY (`informs_id`),
  INDEX `FK_security_informs_idx` (`security_id` ASC) VISIBLE,
  INDEX `FK_secalarm_informs_idx` (`security_alarm_id` ASC) VISIBLE,
  CONSTRAINT `FK_security_informs`
    FOREIGN KEY (`security_id`)
    REFERENCES `Security` (`security_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_securityAlarm_informs`
    FOREIGN KEY (`security_alarm_id`)
    REFERENCES `SecurityAlarm` (`security_alarm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Supports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supports` ;

CREATE TABLE IF NOT EXISTS `Supports` (
  `support_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `atm_machine_id` INT NOT NULL,
  PRIMARY KEY (`support_id`),
  INDEX `FK_atm_supports_idx` (`atm_machine_id` ASC) VISIBLE,
  INDEX `FK_lang_supports_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `FK_atm_supports`
    FOREIGN KEY (`atm_machine_id`)
    REFERENCES `ATMMachine` (`atm_machine_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_language_supports`
    FOREIGN KEY (`language_id`)
    REFERENCES `Languages` (`language_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PaysOff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaysOff` ;

CREATE TABLE IF NOT EXISTS `PaysOff` (
  `pays_off_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `loan_id` INT NOT NULL,
  PRIMARY KEY (`pays_off_id`),
  INDEX `FK_loan_paysOff_idx` (`loan_id` ASC) VISIBLE,
  INDEX `FK_payment_paysOff_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `FK_loan_paysOff`
    FOREIGN KEY (`loan_id`)
    REFERENCES `Loans` (`loan_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_payment_paysOff`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Verifies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Verifies` ;

CREATE TABLE IF NOT EXISTS `Verifies` (
  `verifies_id` INT NOT NULL,
  `keypad_id` INT NOT NULL,
  `NFC_scanner_id` INT NOT NULL,
  `card_reader_id` INT NOT NULL,
  `bank_account_id` INT NOT NULL,
  `verified_at` DATE NULL,
  PRIMARY KEY (`verifies_id`),
  INDEX `FK_nfc_verifies_idx` (`NFC_scanner_id` ASC) VISIBLE,
  INDEX `FK_cardR_verifies_idx` (`card_reader_id` ASC) VISIBLE,
  INDEX `FK_bankacc_verifies_idx` (`bank_account_id` ASC) VISIBLE,
  INDEX `FK_keypad_verifies_idx` (`keypad_id` ASC) VISIBLE,
  CONSTRAINT `FK_keypad_verifies`
    FOREIGN KEY (`keypad_id`)
    REFERENCES `Keypad` (`keypad_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_nfc_verifies`
    FOREIGN KEY (`NFC_scanner_id`)
    REFERENCES `NFCScanner` (`nfc_scanner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_cardR_verifies`
    FOREIGN KEY (`card_reader_id`)
    REFERENCES `CardReader` (`card_reader_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_bankacc_verifies`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `BankAccount` (`bank_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scans` ;

CREATE TABLE IF NOT EXISTS `Scans` (
  `scans_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  `card_reader_id` INT NOT NULL,
  `nfc_scanner_id` INT NOT NULL,
  `scanned` TIMESTAMP NOT NULL,
  PRIMARY KEY (`scans_id`),
  INDEX `FK_card_scans_idx` (`card_id` ASC) VISIBLE,
  INDEX `FK_nfc_scans_idx` (`nfc_scanner_id` ASC) VISIBLE,
  INDEX `FK_cardRea_scans_idx` (`card_reader_id` ASC) VISIBLE,
  CONSTRAINT `FK_card_scans`
    FOREIGN KEY (`card_id`)
    REFERENCES `Card` (`card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_nfcScanner_scans`
    FOREIGN KEY (`nfc_scanner_id`)
    REFERENCES `NFCScanner` (`nfc_scanner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_cardReader_scans`
    FOREIGN KEY (`card_reader_id`)
    REFERENCES `CardReader` (`card_reader_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CashProcess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CashProcess` ;

CREATE TABLE IF NOT EXISTS `CashProcess` (
  `cash_process_id` INT NOT NULL,
  `cash_withdrawal_id` INT NOT NULL,
  `cash_deposit_id` INT NOT NULL,
  `cash_dispenser_id` INT NOT NULL,
  PRIMARY KEY (`cash_process_id`),
  INDEX `FK_cwithdraw_cashpro_idx` (`cash_withdrawal_id` ASC) VISIBLE,
  INDEX `FK_cdeposit_cashpro_idx` (`cash_deposit_id` ASC) VISIBLE,
  INDEX `FK_cdisp_cashpro_idx` (`cash_dispenser_id` ASC) VISIBLE,
  CONSTRAINT `FK_cashWithdraw_cashProcess`
    FOREIGN KEY (`cash_withdrawal_id`)
    REFERENCES `CashWithdrawal` (`cash_withdrawal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_cashDeposit_cashProcess`
    FOREIGN KEY (`cash_deposit_id`)
    REFERENCES `CashDeposit` (`cash_deposit_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_cashDispenser_cashProcess`
    FOREIGN KEY (`cash_dispenser_id`)
    REFERENCES `CashDispenser` (`cash_dispenser_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
